### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by rxgx** [danielpietzsch/CodeRay-GitHub-Theme#1]
What version of CodeRay is this theme for? I have version 1.0.5 and the class for comments is `.comment`.

```
.CodeRay .comment {
    color: #998;
    font-style: italic;
}
```

**Comment by danielpietzsch** [comment]
Yes. That might very well be the case. I am still using version 0.9.8 and there the comment class was just `.c`.

**Comment by danielpietzsch** [comment]
@rxgx Thanks to @johnknott, the stylesheet was updated to work with CodeRay > v1.0.
